version: '3.8'

services:
   mysqldb:
    image: mysql:latest
    container_name: mysqldb
    hostname: mysqldb
    restart: always
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_READ_BUFFER_SIZE: 4M
      MYSQL_SORT_BUFFER_SIZE: 4M
      MYSQL_KEY_BUFFER_SIZE: 64M
      MYSQL_INNODB_BUFFER_POOL_SIZE: 64M
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./docker/data/mysqldb:/var/lib/mysql
      - ./docker/logs/mysqldb:/var/log/mysql
    networks:
      - test-network
networks:
  test-network: